### ISSUE TITLE
Cannot navigate when zoomed into an image on mobile.

### ISSUE THREAD

**Issue by Don404** [andreknieriem/simplelightbox#171]
Hello and thank for your amazing work!

I found something that I think is worth mentioning. When I enter your website https://simplelightbox.com/ and open an image from my mobile phone the zoom works perfectly, however after the image is zoomed in, it can't navigate properly. Every second touch returns the image to the initial place of zoom. 

In other words, if I zoom in the centre of the image and I want to navigate to the corners I get returned in the centre on my second touch.

I was wondering, could this be fixed?

**Comment by andreknieriem** [comment]
Hey, can you tell me on which phone you are and which browser? I can see a problem, that the image moves a little bit when pinching. I will take a look!

**Comment by andreknieriem** [comment]
Fixed

**Comment by Don404** [comment]
Hello and thank you for your quick response. I am using iPhone with Safari and the problem remains. I will try to make a recording so you can see the exact behaviour I am talking about.

I am also making the same test from Samsung with Chrome. And the problem is the same.

Here is an example video recording of the problem:

https://streamable.com/7qdv8e

When I zoom in the centre of the image and try to go to the corners every second touch resets my position to the initial spot where I zoomed.

**Comment by andreknieriem** [comment]
No need to. A user posted a gif here: https://github.com/andreknieriem/simplelightbox/issues/168

**Comment by andreknieriem** [comment]
Ok the bug was on the github page. I've loaded simple-lightbox.js 2.0.0 on that page. Now it works. Please reload sometimes or open with incognito tab.

**Comment by andreknieriem** [comment]
Ok now closed.

**Comment by Don404** [comment]
Thank you very much!! Now it works like a charm.
