### ISSUE TITLE
Object doesn't support this action [IE11]

### ISSUE THREAD

**Issue by ramanprtap** [andreknieriem/simplelightbox#175]
It not working for IE.
![image](https://user-images.githubusercontent.com/42340762/82348501-98b24780-9a16-11ea-87c4-3fb0d59df2fb.png)

**Comment by andreknieriem** [comment]
Working on a solution for that.

**Comment by andreknieriem** [comment]
Fixed. If you need support for IE use simple-lightbox.legacy.js instead.

**Comment by sooroos** [comment]
Hi. i've just tested it in IE 11 and it is still not working. I've used simple-lightbox.legacy.min.js
https://basic.unit08.de/ueber-uns/
