### ISSUE TITLE
[Mobile only] Gallery closes out when pressing next button and cannot be opened again.

### ISSUE THREAD

**Issue by genevievekuzak** [andreknieriem/simplelightbox#294]
Hello, 

I noticed a bug on mobile where sometimes if you press on the edge of the next button, specifically when the image is loading, sometimes the gallery will close out and cannot be opened again. I did a temporary fix by adding 'docClose: false,' to my initialized gallery. This prevents it from happening since the gallery can only be closed by pressing the x button.

**Comment by andreknieriem** [comment]
Hey. Can you try this with the latest version 2.13. I've fixed a lot of these errors.

**Comment by aadfco** [comment]
This issue is still occurring to date with version 2.14.3. 

I tried overriding the size of the click area for the next/prev buttons by setting width and height to 50px in CSS, but the problem still occurs when clicking on the edge of the next button or previous button. I also have swipeClose set to false. 

@genevievekuzak temporary fix is the only thing that resolves the issue.
